Relay endpoints
filetrust/Email-Portal-Test pull request #11
Opened 2020-09-30 13:24 UTC by jaind1046

Added steps for relay endpoint features

2020-09-30 13:24 UTC, jaind1046 commented
@NadHodeGW Relay endpoints tests for review please

2020-09-30 14:47 UTC, NadHodeGW requested changes
1- See comment in transaction-log-view.feature and update
2- new added scenarios in transaction-log-view.feature do not provide any value unless updated to to have an outcome, the Then step should result to a filtered log based on the set or unset filter

2020-09-30 14:47 UTC, NadHodeGW commented on specs/features/transaction-log-view.feature
> +	@TC_Transaction_Logs_Navigation
Invalid scenario syntax, do not have more than 3 when, then or given lines in a scenario; Also, no when step after a then step; please change

2020-09-30 16:43 UTC, werzl approved these changes

2020-10-14 16:24 UTC, jaind1046 commented
Moving to data driven approach. Merge not needed.Closing

2020-10-14 16:24 UTC, closed without merging